// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPITemplete.DBContexts.EFCore;

#nullable disable

namespace WebAPITemplete.DBContexts.EFCore.Migrations.Test1
{
    [DbContext(typeof(ProjectDBContext_Test1))]
    [Migration("20230510065908_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webAPITemplete.Models.Entities.TestDB1.TestTable01", b =>
                {
                    b.Property<int>("ID_1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_1"));

                    b.Property<int>("ID_2")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("TestCol01")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("TestCol02")
                        .HasColumnType("int");

                    b.HasKey("ID_1", "ID_2");

                    b.ToTable("TestTable01");
                });
#pragma warning restore 612, 618
        }
    }
}
